#!/usr/bin/env python
# encoding: utf-8

from waflib.Build import BuildContext
import os,re

APPNAME = 'property.exe'
LIBNAME = 'property'
VERSION = '0.0.1'

top = '.'
out = 'BUILD'

def options(ctx):
        ctx.load('compiler_cxx')

def configure(ctx):
    #print('→ configuring the project in ' + ctx.path.abspath())
    ctx.load('compiler_cxx')
    ctx.load('clang_compilation_database')

def is_clang():
    try:
        cxx = os.environ['CXX']
    except:
        return False

    if re.match('clang.*', cxx):
        return True
    return False

def build(ctx):
    #for attr in dir(ctx):
        #print("obj.%s = %r" % (attr, getattr(ctx, attr)))

    mycxxflags          = ['-ggdb', '-std=c++11', '-Wall', '-Wpedantic', '-Werror', '-Wextra', '-Wshadow',]
    mycxxflags         += ['-Wformat=2',]

    if is_clang():
        mycxxflags     += ['-Weverything']

    ctx.program(
            target       = APPNAME,
            source       = ['main.cpp'],
            includes     = ['.'],
            linkflags    = ['-ggdb'],
            cxxflags     = mycxxflags,
            use          = [LIBNAME],
    )
    ctx.stlib(
            target       = LIBNAME,
            source       = ['options.cpp', 'config.cpp', 'utils.cpp', 'settings.cpp', 'settings_storage.cpp'],
            includes     = ['.'],
            linkflags    = ['-ggdb'],
            cxxflags     = mycxxflags,
    )
